# Generated by Django 4.2.9 on 2024-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
